#自动调用api保活，模仿人为开发版
name: Auto Api Human

on: 
  release:
    types: [published]
  push:
    # tags:
    # - 'v*'
    branches: 
    - main
  schedule:
    - cron: "0 9,13,16 * * 1-5"
  watch:
    types: [started]
  repository_dispatch:
    types: [webapi]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: |
        pip install requests
    - name: Read config from secrets  #读取机密
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }} # secrets_id 提供
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }} # secrets_key 提供
        ID: ${{ secrets.ID }}
        KEY: ${{ secrets.KEY }}
      run: | 
        cp 1.py 2.py
        echo $CONFIG_ID > configid.txt
        echo $CONFIG_KEY > configkey.txt
        sed -i '10 r configid.txt' 2.py
        sed -i '12 r configkey.txt' 2.py
        
    - name: Test Api #Api调用
      run: | 
        python 1.py --ID ${{ secrets.ID }} --KEY ${{ secrets.KEY }}
